### ISSUE TITLE
Mark Complete Button Links Don't Function

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms-lite-lms-progress-tracker#15] opened 2020-08-08 02:15 UTC
### Reproduction Steps

+ Install & activate Lite LMS
+ Create 3 pages. 
+ Add Lite LMS block
+ Add Incomplete message and complete message
+ Add link to buttons
+ Complete 1 page on the front end
+ Notice button clicks do not create redirect

View this test environment: https://lms-lite-test.myliftersite.com/

### Expected Behavior

+ Completing the block on one post would redirect to the specified link

### Actual Behavior

+ All button links mark the current post, but no redirect on click occurs

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

This issue has be recreated:
+ [ ] Locally
+ [X] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
Chrome
+ Operating System name and version
OSX
+ Device name and version (if applicable)
MacBook Pro

**Comment by eri-trabiccolo** [comment] 2020-08-08 16:57
see also #3

**Comment by thomasplevy** [comment] 2020-08-10 15:47
Duplicate of #3

**Closed as completed by thomasplevy** 2020-08-10 15:47 UTC
Labels: Status: Has PR
